"""add target_column to schema_mappings

Revision ID: 97468adb7cb9
Revises: 7e3a91c4bd28
Create Date: 2026-05-13 08:04:53.860670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97468adb7cb9'
down_revision: Union[str, None] = '7e3a91c4bd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_mappings', sa.Column('target_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_mappings', 'target_column')
    # ### end Alembic commands ###
