"""FastAPI surface for the hackathon submission.

Two endpoints (one per task) backed by Entivia's ``BaseAgent`` ReAct loop.
The schemas live in :mod:`hackathon.app.schemas`; the agents live under
:mod:`hackathon.agents`.
"""

from __future__ import annotations

import logging

from fastapi import FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware

from hackathon.agents.recommender import RecommendationAgent
from hackathon.agents.review_simulator import ReviewSimulationAgent
from hackathon.app.schemas import (
    HealthResponse,
    MetricsResponse,
    RecommendRequest,
    RecommendResponse,
    SampleUsersResponse,
    SimulateReviewRequest,
    SimulateReviewResponse,
)
from hackathon.core.repository import list_sample_user_ids
from hackathon.eval.metrics import load_eval_snapshot

logger = logging.getLogger("hackathon.api")
logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s | %(message)s")

TAG_SYSTEM = "System"
TAG_DEMO = "Demo helpers"
TAG_TASK_A = "Task A — Review simulation"
TAG_TASK_B = "Task B — Recommendations"


app = FastAPI(
    title="Entivia — DSN x Bluechip LLM Agent Challenge",
    description=(
        "A containerized FastAPI demo for the DSN x Bluechip LLM Agent Challenge.\n\n"
        "## What it demonstrates\n"
        "- **Task A — Review simulation:** accepts **persona + product** (direct mode) or "
        "`user_id` + `item_id` (DB demo); returns star rating + review text.\n"
        "- **Two submission containers:** Task A `:8011`, Task B `:8012` (this gateway `:8010` "
        "exposes both).\n"
        "- **Task B — Recommendations:** combines local BGE embeddings in Qdrant with "
        "Entivia's `BaseAgent` for warm-start, cold-start, multi-turn, and cross-domain "
        "recommendations.\n"
        "- **No embedding API dependency:** `fastembed` runs inside Docker and caches the "
        "model in a Docker volume.\n"
        "- **Measurable agents:** every response includes runtime `meta`, and "
        "`GET /metrics` exposes the latest evaluation report.\n\n"
        "Start with `GET /samples/users`, then try `POST /simulate-review` and "
        "`POST /recommend` using the examples in Swagger."
    ),
    version="1.0.0",
    contact={"name": "Entivia / Pulse AI"},
    license_info={"name": "Hackathon submission"},
    openapi_tags=[
        {"name": TAG_SYSTEM, "description": "Health and metadata."},
        {"name": TAG_DEMO, "description": "Helpers for discovering real ids to test with."},
        {"name": TAG_TASK_A, "description": "Predict stars and review text for a user × item pair."},
        {"name": TAG_TASK_B, "description": "Personalized recommendations across cold/warm/cross-domain modes."},
    ],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get(
    "/healthz",
    tags=[TAG_SYSTEM],
    summary="Health check",
    response_model=HealthResponse,
    description="Lightweight readiness probe for the hackathon API container.",
)
async def healthz() -> HealthResponse:
    return HealthResponse()


@app.get(
    "/samples/users",
    tags=[TAG_DEMO],
    summary="List sample warm-start users",
    response_model=SampleUsersResponse,
    description=(
        "Returns real loaded user ids you can paste into `/simulate-review` or "
        "`/recommend`. Use `dataset=yelp` for the main challenge dataset."
    ),
)
async def sample_users(
    dataset: str = Query("yelp", description="Dataset to sample from, usually `yelp`."),
    limit: int = Query(5, ge=1, le=50, description="Maximum number of user ids to return."),
) -> SampleUsersResponse:
    user_ids = await list_sample_user_ids(dataset, limit)
    return SampleUsersResponse(dataset=dataset, user_ids=user_ids)


@app.get(
    "/metrics",
    tags=[TAG_DEMO],
    summary="Show latest evaluation metrics",
    response_model=MetricsResponse,
    description=(
        "Returns the most recent metrics generated by `python -m hackathon.eval.run`: "
        "Task A RMSE/ROUGE-L, Task B Hit@10/NDCG@10, and baseline ablations. "
        "If no eval has been run, `available=false` explains how to generate it."
    ),
)
async def metrics() -> MetricsResponse:
    return MetricsResponse(**load_eval_snapshot().to_dict())


@app.post(
    "/simulate-review",
    tags=[TAG_TASK_A],
    summary="Simulate a user's review for an item",
    response_model=SimulateReviewResponse,
    description=(
        "Runs the ReviewSimulationAgent. **Direct mode:** send `persona` + `product` "
        "objects (challenge spec). **DB mode:** send `user_id` + `item_id` to load "
        "profile and item from Postgres. Returns stars, text, and runtime `meta`. "
        "Use `voice=nigerian` for the localization bonus."
    ),
)
async def simulate_review(req: SimulateReviewRequest) -> SimulateReviewResponse:
    agent = ReviewSimulationAgent()
    try:
        if req.persona and req.product:
            result = await agent.simulate(
                persona=req.persona.to_agent_dict(),
                product=req.product.to_agent_dict(),
                voice=req.voice,
            )
        else:
            result = await agent.simulate(
                user_id=req.user_id,
                item_id=req.item_id,
                voice=req.voice,
            )
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except RuntimeError as exc:
        logger.warning("simulate-review failed: %s", exc)
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    except Exception as exc:  # last-resort guard so the container never 500s silently
        logger.exception("simulate-review crashed")
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc)) from exc
    return SimulateReviewResponse(**result)


@app.post(
    "/recommend",
    tags=[TAG_TASK_B],
    summary="Generate personalized recommendations",
    response_model=RecommendResponse,
    description=(
        "Runs the RecommendationAgent. For warm-start users, it builds a persona "
        "vector from real review history and excludes already-reviewed items. For "
        "cold-start, it embeds the free-text persona. Qdrant retrieves candidates; "
        "the LLM reranks them and explains each recommendation. Pass a returned "
        "`conversation_id` plus `follow_up` for multi-turn refinement. Use "
        "`dataset=goodreads` to demonstrate cross-domain recommendations."
    ),
)
async def recommend(req: RecommendRequest) -> RecommendResponse:
    if not req.user_id and not req.persona:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            detail="Provide either `user_id` (warm-start) or `persona` (cold-start).",
        )
    try:
        result = await RecommendationAgent().recommend(
            user_id=req.user_id,
            persona=req.persona,
            k=req.k,
            dataset=req.dataset,
            conversation_id=req.conversation_id,
            follow_up=req.follow_up,
        )
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except Exception as exc:
        logger.exception("recommend crashed")
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc)) from exc
    return RecommendResponse(**result)
